# PreToolUse hook: blocks Edit/Write on EF-generated migration artifacts.
# The model snapshot and the *.Designer.cs files are regenerated by
# `scripts/AddMigration.ps1` (dotnet-ef) — hand-editing them silently desyncs
# the EF model from the schema in ways the InMemory tests won't catch.
# Reads the hook JSON payload from stdin; exit 2 = block the tool call.
#
# Note: this only fires on the Edit/Write TOOLS. The /add-migration skill writes
# these files via dotnet-ef inside AddMigration.ps1, not via Edit/Write, so the
# sanctioned migration flow is unaffected. The plain migration up/down .cs file
# is intentionally NOT blocked — it is sometimes hand-tuned for custom SQL.
$payload = [Console]::In.ReadToEnd() | ConvertFrom-Json
$path = $payload.tool_input.file_path
if (-not $path) { exit 0 }

$blocked = @(
    'ApplicationDbContextModelSnapshot\.cs$', # EF model snapshot — regenerate only
    '\.Designer\.cs$'                          # migration metadata — regenerate only
)

foreach ($pattern in $blocked) {
    if ($path -match $pattern) {
        [Console]::Error.WriteLine("Blocked: '$path' is EF-generated. Change the entity model and run /add-migration (scripts/AddMigration.ps1) instead of editing this file by hand.")
        exit 2
    }
}
exit 0
