DROP TABLE [dbo].[__EFMigrationsHistory]
DROP TABLE [dbo].[TrackedTask]
DROP TABLE [dbo].[Project]
DROP TABLE [dbo].[Companies]
DROP TABLE [dbo].[AspNetRoleClaims]
DROP TABLE [dbo].[AspNetRoles]
DROP TABLE [dbo].[AspNetUserClaims]
DROP TABLE [dbo].[AspNetUserLogins]
DROP TABLE [dbo].[AspNetUserRoles]
DROP TABLE [dbo].[AspNetUsers]
DROP TABLE [dbo].[AspNetUserTokens]
DROP TABLE [dbo].[DeviceCodes]
DROP TABLE [dbo].[PersistedGrants]
DROP TABLE [dbo].[Keys]
GO
