DROP TABLE IF EXISTS [dbo].[__EFMigrationsHistory]
DROP TABLE IF EXISTS [dbo].[TrackedTasks]
DROP TABLE IF EXISTS [dbo].[Projects]
DROP TABLE IF EXISTS [dbo].[AspNetRoleClaims]
DROP TABLE IF EXISTS [dbo].[AspNetUserClaims]
DROP TABLE IF EXISTS [dbo].[AspNetUserLogins]
DROP TABLE IF EXISTS [dbo].[AspNetUserRoles]
DROP TABLE IF EXISTS [dbo].[AspNetUserTokens]
DROP TABLE IF EXISTS [dbo].[AspNetUsers]
DROP TABLE IF EXISTS [dbo].[AspNetRoles]
GO
